# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mkk-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mkk-iOS
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
    pod 'RealmSwift'
  pod 'SwipeCellKit'
  target 'Mkk-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
